apiVersion: v1
kind: PersistentVolume
metadata:
  name: hub-db-pv
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    namespace: jhub
    name: hub-db-dir
  hostPath:
    path: "/srv/jupyterhub"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - <NODE-NAME>
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
